BEGIN TRANSACTION;

ALTER TABLE Submissions ADD COLUMN "D3D12_FEATURE_DATA_D3D12_OPTIONS21.WorkGraphsTier" INT;
ALTER TABLE Submissions ADD COLUMN "D3D12_FEATURE_DATA_D3D12_OPTIONS21.ExecuteIndirectTier" INT;
ALTER TABLE Submissions ADD COLUMN "D3D12_FEATURE_DATA_D3D12_OPTIONS21.SampleCmpGradientAndBiasSupported" INT;
ALTER TABLE Submissions ADD COLUMN "D3D12_FEATURE_DATA_D3D12_OPTIONS21.ExtendedCommandInfoSupported" INT;

PRAGMA user_version=3;

COMMIT;
